/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiSendNewsletterRouteImport } from './routes/api/send-newsletter'
import { Route as BlogSlugOpengraphImageRouteImport } from './routes/blog.$slug.opengraph-image'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendNewsletterRoute = ApiSendNewsletterRouteImport.update({
  id: '/api/send-newsletter',
  path: '/api/send-newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugOpengraphImageRoute = BlogSlugOpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => BlogSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/opengraph-image': typeof OpengraphImageRoute
  '/partners': typeof PartnersRoute
  '/api/send-newsletter': typeof ApiSendNewsletterRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/blog/$slug/opengraph-image': typeof BlogSlugOpengraphImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/partners': typeof PartnersRoute
  '/api/send-newsletter': typeof ApiSendNewsletterRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog': typeof BlogIndexRoute
  '/blog/$slug/opengraph-image': typeof BlogSlugOpengraphImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/opengraph-image': typeof OpengraphImageRoute
  '/partners': typeof PartnersRoute
  '/api/send-newsletter': typeof ApiSendNewsletterRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/blog/$slug/opengraph-image': typeof BlogSlugOpengraphImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/opengraph-image'
    | '/partners'
    | '/api/send-newsletter'
    | '/api/subscribe'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/$slug/opengraph-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/opengraph-image'
    | '/partners'
    | '/api/send-newsletter'
    | '/api/subscribe'
    | '/blog/$slug'
    | '/blog'
    | '/blog/$slug/opengraph-image'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/opengraph-image'
    | '/partners'
    | '/api/send-newsletter'
    | '/api/subscribe'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/$slug/opengraph-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  OpengraphImageRoute: typeof OpengraphImageRoute
  PartnersRoute: typeof PartnersRoute
  ApiSendNewsletterRoute: typeof ApiSendNewsletterRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-newsletter': {
      id: '/api/send-newsletter'
      path: '/api/send-newsletter'
      fullPath: '/api/send-newsletter'
      preLoaderRoute: typeof ApiSendNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/opengraph-image': {
      id: '/blog/$slug/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/blog/$slug/opengraph-image'
      preLoaderRoute: typeof BlogSlugOpengraphImageRouteImport
      parentRoute: typeof BlogSlugRoute
    }
  }
}

interface BlogSlugRouteChildren {
  BlogSlugOpengraphImageRoute: typeof BlogSlugOpengraphImageRoute
}

const BlogSlugRouteChildren: BlogSlugRouteChildren = {
  BlogSlugOpengraphImageRoute: BlogSlugOpengraphImageRoute,
}

const BlogSlugRouteWithChildren = BlogSlugRoute._addFileChildren(
  BlogSlugRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  OpengraphImageRoute: OpengraphImageRoute,
  PartnersRoute: PartnersRoute,
  ApiSendNewsletterRoute: ApiSendNewsletterRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
