name: Send Newsletter for New Blog Posts

on:
  push:
    branches: [main]
    paths: ['posts/*.mdx']

jobs:
  send-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch current and previous commit to compare changes

      - name: Send newsletter for new posts
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          NEWSLETTER_SECRET: ${{ secrets.NEWSLETTER_SECRET }}
        run: bash scripts/send-newsletter.sh
